IO.stream()
|> Enum.map(&String.split/1)
|> Enum.map(fn l -> Enum.map(l, &String.to_integer/1) |> List.to_tuple end)
|> Enum.unzip()
|> Tuple.to_list()
|> Enum.map(&Enum.sort/1)
|> Enum.zip()
|> Enum.map(fn {l, r} -> abs(l - r) end)
|> Enum.sum()
|> IO.inspect()
